### ISSUE TITLE
Cool Project! Takes a long time to install though

### ISSUE THREAD

**Issue by nebrelbug** [rahmanda/ambercat#1]
This looks like a really cool package!

One problem: it takes a very long time to install because of all its dependencies. Is there any way you could get rid of some of them or use lighter-weight versions?

A cool tool: https://github.com/siddharthkp/cost-of-modules

Looking forward to using this!

**Comment by rahmanda** [comment]
Hello, thanks for reporting.

Based on cost-of-modules, browser-sync was the largest dependency on this package. I tried to get rid of it on PR #5. It should reduce at least 30% of load size. The changes was just published on version `0.4.3`. What do you think?

**Comment by nebrelbug** [comment]
Thanks @rahmanda! I'll check it out with the recent changes.
